### PR TITLE
Add support for x-forwarded-prefix header

### PR DESCRIPTION
**Pull request by math-nao**
Use case: document server listens on the root path (/) but should be routeable on a specific prefix (/document-server for example). Currently, the only workaround is to add prefix path into x-forwarded-host header value.

### CODE REVIEW

**Comment by ShockwaveNN** [comment]
Hi, thanks for your conribution, first of all - change base branch to develop, we only accept third-party PR to develop

**Comment by math-nao** [comment]
@ShockwaveNN changes requested have been done. any news?

**Comment by agolybev** [comment]
Hi @math-nao, what reverse proxy uses the header? You can use `X-Forwarded-Host` to specify a virtual path. Put it together with a hostname. For example: `example.com/vpath`

**Comment by math-nao** [comment]
Hi @agolybev , I know, I’m currently using this as a workaround in my reverse proxy. Issue is that `X-Forwarded-Host` is for setting host and port only not for setting URL path.
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-Host

**Pull request merged**
